version: "3"
services:
  node-app:
      build: .
      ports:
        - "3002:4000"
      env_file:
        - ./.env

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rancid
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
